services:
  - type: web
    name: cyber-crime-reporting
    env: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "gunicorn app:app --workers 1 --timeout 120"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: APP_PUBLIC_URL
        sync: false
